In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
load_boston()

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [2]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [3]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [4]:
load_boston()['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [5]:
df=pd.DataFrame(data=X, columns=load_boston()['feature_names'])
df['house-price']=y
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  house-price  
0       15.3  396.90   4.98         24.0  
1       17.8  396.90   9.14         21.6  
2       17.8  392.83   4.03         34.7  
3       18.7  394.63   2.94         33.4  
4       18.7  396.90   5.33         36.2  
..       ...     ...    ...          ...  
501     21.0  391.99   9.67         22.4  
502     21.0  396.90   9.08         20.6  
503     21.0  396.90   5.64         23.9  
504     21.0  393.45   6.48         22.0  
505     21.0  396.90   7.88         11.9  

[506 rows x 14 columns]

In [6]:
from sklearn.model_selection import train_test_split
X, y = df.iloc[:,:-1],df.iloc[:,[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [7]:
X_train

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS   RAD    TAX  \
445  10.67180   0.0  18.10   0.0  0.740  6.459  94.8   1.9879  24.0  666.0   
428   7.36711   0.0  18.10   0.0  0.679  6.193  78.1   1.9356  24.0  666.0   
481   5.70818   0.0  18.10   0.0  0.532  6.750  74.9   3.3317  24.0  666.0   
55    0.01311  90.0   1.22   0.0  0.403  7.249  21.9   8.6966   5.0  226.0   
488   0.15086   0.0  27.74   0.0  0.609  5.454  92.7   1.8209   4.0  711.0   
..        ...   ...    ...   ...    ...    ...   ...      ...   ...    ...   
486   5.69175   0.0  18.10   0.0  0.583  6.114  79.8   3.5459  24.0  666.0   
189   0.08370  45.0   3.44   0.0  0.437  7.185  38.9   4.5667   5.0  398.0   
495   0.17899   0.0   9.69   0.0  0.585  5.670  28.8   2.7986   6.0  391.0   
206   0.22969   0.0  10.59   0.0  0.489  6.326  52.5   4.3549   4.0  277.0   
355   0.10659  80.0   1.91   0.0  0.413  5.936  19.5  10.5857   4.0  334.0   

     PTRATIO       B  LSTAT  
445     20.2   43.06  23.98  
428     20.2   96.73  21.52  
481     20.2  393.07   7.74  
55      17.9  395.93   4.81  
488     20.1  395.09  18.06  
..       ...     ...    ...  
486     20.2  392.68  14.98  
189     15.2  396.90   5.39  
495     19.2  393.29  17.60  
206     18.6  394.87  10.97  
355     22.0  376.04   5.57  

[354 rows x 13 columns]

In [8]:
X_test

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
226   0.38214   0.0   6.20   0.0  0.504  8.040   86.5  3.2157   8.0  307.0   
292   0.03615  80.0   4.95   0.0  0.411  6.630   23.4  5.1167   4.0  245.0   
90    0.04684   0.0   3.41   0.0  0.489  6.417   66.1  3.0923   2.0  270.0   
373  11.10810   0.0  18.10   0.0  0.668  4.906  100.0  1.1742  24.0  666.0   
273   0.22188  20.0   6.96   1.0  0.464  7.691   51.8  4.3665   3.0  223.0   
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
60    0.14932  25.0   5.13   0.0  0.453  5.741   66.2  7.2254   8.0  284.0   
108   0.12802   0.0   8.56   0.0  0.520  6.474   97.1  2.4329   5.0  384.0   
298   0.06466  70.0   2.24   0.0  0.400  6.345   20.1  7.8278   5.0  358.0   
138   0.24980   0.0  21.89   0.0  0.624  5.857   98.2  1.6686   4.0  437.0   
370   6.53876   0.0  18.10   1.0  0.631  7.016   97.5  1.2024  24.0  666.0   

     PTRATIO       B  LSTAT  
226     17.4  387.38   3.13  
292     19.2  396.90   4.70  
90      17.8  392.18   8.81  
373     20.2  396.90  34.77  
273     18.6  390.77   6.58  
..       ...     ...    ...  
60      19.7  395.11  13.15  
108     20.9  395.24  12.27  
298     14.8  368.24   4.97  
138     21.2  392.04  21.32  
370     20.2  392.05   2.96  

[152 rows x 13 columns]

In [9]:
from sklearn.preprocessing import StandardScaler
data = X_train
scaler = StandardScaler()

In [10]:
scaler.fit_transform(data)

array([[ 0.87550928, -0.49961764,  1.06960848, ...,  0.81091271,
        -3.46382037,  1.61136934],
       [ 0.47466521, -0.49961764,  1.06960848, ...,  0.81091271,
        -2.87288804,  1.26563608],
       [ 0.27344444, -0.49961764,  1.06960848, ...,  0.81091271,
         0.3899569 , -0.67103236],
       ...,
       [-0.3972215 , -0.49961764, -0.18207157, ...,  0.34307845,
         0.39237921,  0.71471153],
       [-0.39107182, -0.49961764, -0.04812246, ...,  0.0623779 ,
         0.40977576, -0.21708177],
       [-0.4060033 ,  3.00699239, -1.33998725, ...,  1.65301436,
         0.20244847, -0.97600844]])

In [11]:
X_train = pd.DataFrame(scaler.fit_transform(data),index=X_train.index, columns=X_train.columns)
X_train

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
445  0.875509 -0.499618  1.069608 -0.251124  1.645428  0.233772  0.969882   
428  0.474665 -0.499618  1.069608 -0.251124  1.113435 -0.149715  0.383159   
481  0.273444 -0.499618  1.069608 -0.251124 -0.168580  0.653301  0.270733   
55  -0.417342  3.445319 -1.442682 -0.251124 -1.293614  1.372699 -1.591321   
488 -0.400634 -0.499618  2.504352 -0.251124  0.502952 -1.215116  0.896102   
..        ...       ...       ...       ...       ...       ...       ...   
486  0.271452 -0.499618  1.069608 -0.251124  0.276201 -0.263608  0.442885   
189 -0.408780  1.472851 -1.112274 -0.251124 -0.997094  1.280432 -0.994058   
495 -0.397222 -0.499618 -0.182072 -0.251124  0.293643 -0.903713 -1.348902   
206 -0.391072 -0.499618 -0.048122 -0.251124 -0.543592  0.042029 -0.516248   
355 -0.406003  3.006992 -1.339987 -0.251124 -1.206402 -0.520227 -1.675640   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
445 -0.900522  1.654486  1.538813  0.810913 -3.463820  1.611369  
428 -0.926152  1.654486  1.538813  0.810913 -2.872888  1.265636  
481 -0.241993  1.654486  1.538813  0.810913  0.389957 -0.671032  
55   2.387078 -0.527917 -1.061095 -0.265106  0.421447 -1.082820  
488 -0.982361 -0.642780  1.804713  0.764129  0.412198  0.779361  
..        ...       ...       ...       ...       ...       ...  
486 -0.137024  1.654486  1.538813  0.810913  0.385663  0.346492  
189  0.363219 -0.527917 -0.044767 -1.528259  0.432127 -1.001306  
495 -0.503239 -0.413054 -0.086129  0.343078  0.392379  0.714712  
206  0.259426 -0.642780 -0.759742  0.062378  0.409776 -0.217082  
355  3.312831 -0.642780 -0.422936  1.653014  0.202448 -0.976008  

[354 rows x 13 columns]

In [12]:
X_test = pd.DataFrame(scaler.transform(X_test),index=X_test.index, columns=X_test.columns)
X_test

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
226 -0.372580 -0.499618 -0.701496 -0.251124 -0.412774  2.513068  0.678277   
292 -0.414547  3.006992 -0.887537 -0.251124 -1.223845  0.480299 -1.538621   
90  -0.413251 -0.499618 -1.116739 -0.251124 -0.543592  0.173222 -0.038438   
373  0.928431 -0.499618  1.069608 -0.251124  1.017502 -2.005157  1.152574   
273 -0.392019  0.377035 -0.588384  3.982103 -0.761621  2.009922 -0.540841   
..        ...       ...       ...       ...       ...       ...       ...   
60  -0.400820  0.596198 -0.860747 -0.251124 -0.857555 -0.801354 -0.034925   
108 -0.403404 -0.499618 -0.350252 -0.251124 -0.273235  0.255397  1.050688   
298 -0.411089  2.568666 -1.290873 -0.251124 -1.319778  0.069421 -1.654560   
138 -0.388633 -0.499618  1.633683 -0.251124  0.633770 -0.634119  1.089334   
370  0.374190 -0.499618  1.069608  3.982103  0.694818  1.036788  1.064741   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
226 -0.298839 -0.183327 -0.582476 -0.499023  0.327307 -1.318931  
292  0.632747 -0.642780 -0.948826  0.343078  0.432127 -1.098280  
90  -0.359311 -0.872507 -0.801104 -0.311890  0.380158 -0.520652  
373 -1.299276  1.654486  1.538813  0.810913  0.432127  3.127817  
273  0.265111 -0.757644 -1.078822  0.062378  0.364633 -0.834061  
..        ...       ...       ...       ...       ...       ...  
60   1.666116 -0.183327 -0.718380  0.576996  0.412418  0.089300  
108 -0.682450 -0.527917 -0.127492  1.138397  0.413850 -0.034377  
298  1.961322 -0.527917 -0.281123 -1.715392  0.116567 -1.060334  
138 -1.056995 -0.642780  0.185679  1.278747  0.378616  1.237528  
370 -1.285457  1.654486  1.538813  0.810913  0.378726 -1.342823  

[152 rows x 13 columns]

In [13]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X_train, y_train)
reg.score(X_train, y_train) #returns the r-square coefficient of train data

0.7611598772034452

In [14]:
reg.coef_

array([[-1.27363359,  0.94438381, -0.17050408,  0.18568703, -1.48334986,
         2.80195533, -0.29987372, -2.72418289,  2.77088061, -2.13961719,
        -2.08896111,  1.15085564, -3.28764536]])

In [15]:
reg.intercept_

array([22.55621469])

In [16]:
y_pred=reg.predict(X_test)
y_pred

array([[37.38997666],
       [31.56794193],
       [27.13373886],
       [ 6.55117625],
       [33.69310848],
       [ 5.54919368],
       [27.10005629],
       [29.82980986],
       [26.44622421],
       [22.38873525],
       [32.24739998],
       [21.74892356],
       [23.42369575],
       [33.57974607],
       [28.31450393],
       [15.36502049],
       [ 0.17012738],
       [18.7085528 ],
       [14.6046344 ],
       [10.80263809],
       [ 3.18552876],
       [19.39248482],
       [38.33235502],
       [24.40456217],
       [31.99950162],
       [11.35200963],
       [24.922899  ],
       [23.39214933],
       [22.75072363],
       [21.09584945],
       [16.12295584],
       [ 7.53544865],
       [17.59797845],
       [22.82206974],
       [29.26790527],
       [18.8053497 ],
       [28.33669828],
       [ 8.60467923],
       [41.63227506],
       [34.1975156 ],
       [20.11767808],
       [ 4.30987094],
       [29.61105614],
       [11.92148423],
       [27.22215387],
       [30

In [17]:
# for comparing predicted and actual values side by side
np.concatenate((y_pred.reshape(len(y_pred),1), y_test.values.reshape(len(y_test),1)),1)

array([[37.38997666, 37.6       ],
       [31.56794193, 27.9       ],
       [27.13373886, 22.6       ],
       [ 6.55117625, 13.8       ],
       [33.69310848, 35.2       ],
       [ 5.54919368, 10.4       ],
       [27.10005629, 23.9       ],
       [29.82980986, 29.        ],
       [26.44622421, 22.8       ],
       [22.38873525, 23.2       ],
       [32.24739998, 33.2       ],
       [21.74892356, 19.        ],
       [23.42369575, 20.3       ],
       [33.57974607, 36.1       ],
       [28.31450393, 24.4       ],
       [15.36502049, 17.2       ],
       [ 0.17012738, 17.9       ],
       [18.7085528 , 19.6       ],
       [14.6046344 , 19.7       ],
       [10.80263809, 15.        ],
       [ 3.18552876,  8.1       ],
       [19.39248482, 23.        ],
       [38.33235502, 44.8       ],
       [24.40456217, 23.1       ],
       [31.99950162, 32.2       ],
       [11.35200963, 10.8       ],
       [24.922899  , 23.1       ],
       [23.39214933, 21.2       ],
       [22.75072363,

In [18]:
reg.score(X_test, y_test)

0.6771696999851695