In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('C:\\Users\\soham\\Downloads\\LinearRegression.csv')
df 

x  y
0  2  1
1  3  2
2  1  2
3  1  1
4  0  1
5  5  3
6  4  3
7  6  7
8  5  6
9  3  5

In [2]:
def MeanSquaredError(Y_true,Y_pred):
    MSE = np.square(np.subtract(Y_true,Y_pred)).mean() 
    return MSE

Y_true = [1,1,2,2,4]
Y_pred = [0.6,1.29,1.99,2.69,3.4]

MeanSquaredError(Y_true,Y_pred)   

0.21606

In [3]:
def gradient_descent_regularization(X, y_true, lr=0.05, epoch=100, lamda=0.1): #updating m and c till fixed number of iteration/epoch,by default epoch=100
    
    '''
    Gradient Descent for a single feature
    '''
    
    m, c = 3,2 # parameters
    logs, mse = [], [] # lists to store learning process
    N = len(X) # number of samples
    
    for i in range(epoch):
        
        y_pred = (m*X + c)
        diff = y_pred - y_true 
        
        MSE= MeanSquaredError(y_true, y_pred)
        print('The Mean Squared Error of epoch ',i,' is ',MSE)
        
        logs.append((m, c))
        mse.append(MSE)
        
        # lists for plotting purposes
        mse_list.append(MSE)
        m_list.append(m)
        c_list.append(c)
        
        m -= lr * ((2 * np.dot(X,diff).sum() / N) + 2*lamda*m)  # acc to gradient descent eqn, this is m(new) = (m(old) + α * ∂(MSE)/∂m ) , where α is learning rate
        # added the regularization factor '2*lamda*m', in the calculation of ∂(MSE)/∂m, no changes in clculation of 'c'
        c -= lr * (2 * diff.sum() / N)  # acc to gradient descent eqn, this is c(new) = (c(old) + α * ∂(MSE)/∂c ) , where α is learning rate
        
    print('The Final Value of m is : ',m)
    print('The Final Value of c is : ',c)
    print('The Minimum Value of MSE is : ',min(mse))
    
           
    return logs, mse

In [4]:
# lists for plotting purposes
mse_list=[]
m_list=[]
c_list=[]

X=df['x']
y=df['y']
gradient_descent_regularization(X, y, lr=0.01, epoch=100)

The Mean Squared Error of epoch  0  is  79.9
The Mean Squared Error of epoch  1  is  43.4972424
The Mean Squared Error of epoch  2  is  24.032420540646395
The Mean Squared Error of epoch  3  is  13.62700659893446
The Mean Squared Error of epoch  4  is  8.066259288284364
The Mean Squared Error of epoch  5  is  5.095662793659487
The Mean Squared Error of epoch  6  is  3.509414965827829
The Mean Squared Error of epoch  7  is  2.6627275460350885
The Mean Squared Error of epoch  8  is  2.210896671512855
The Mean Squared Error of epoch  9  is  1.9697088347121352
The Mean Squared Error of epoch  10  is  1.8407661456197855
The Mean Squared Error of epoch  11  is  1.7715443152817563
The Mean Squared Error of epoch  12  is  1.734031882379788
The Mean Squared Error of epoch  13  is  1.7133090868972272
The Mean Squared Error of epoch  14  is  1.7014430829133538
The Mean Squared Error of epoch  15  is  1.6942261698845797
The Mean Squared Error of epoch  16  is  1.6894340261895509
The Mean Squared E

([(3, 2),
  (2.368, 1.842),
  (1.906008, 1.7250800000000002),
  (1.568377168, 1.6382179200000002),
  (1.321716292128, 1.5733509315200003),
  (1.141599298036288, 1.5245809353619202),
  (1.0101582202133557, 1.4875933587725045),
  (0.914322430752813, 1.4592319983842532),
  (0.8445306134385433, 1.4371880125713994),
  (0.7937885568708694, 1.4197724155136588),
  (0.756979918494849, 1.4057496537911336),
  (0.7303620399696894, 1.39421586560562),
  (0.7111971298810511, 1.3845098258953263),
  (0.6974824693375445, 1.3761478015845567),
  (0.6877530540307348, 1.368775897392613),
  (0.6809372244633715, 1.3621351962029167),
  (0.6762510576775002, 1.3560362588110562),
  (0.6731211134987517, 1.350340470174185),
  (0.6711279224596176, 1.3449463939607762),
  (0.6699646465172282, 1.3397797907339837),
  (0.6694068388578133, 1.3347863161282703),
  (0.6692903228202325, 1.329926179474236),
  (0.6694950100554393, 1.3251702365155373),
  (0.6699330633104255, 1.3204971311819003),
  (0.6705402373586634, 1.31589120

# using sklearn Ridge :-

In [55]:
X = df.iloc[:, :-1]
y = df.iloc[:, [-1]]

In [56]:
#without train test split
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0, max_iter=1000)
clf.fit(X, y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [57]:
clf.coef_

array([[0.86486486]])

In [58]:
clf.intercept_

array([0.50540541])

### the 'm' and 'c' values came different because sklearn calculates learning rate (α) differently

In [59]:
clf.n_iter_

In [60]:
clf.predict(X)

array([[2.23513514],
       [3.1       ],
       [1.37027027],
       [1.37027027],
       [0.50540541],
       [4.82972973],
       [3.96486486],
       [5.69459459],
       [4.82972973],
       [3.1       ]])

In [61]:
MeanSquaredError(y,clf.predict(X))

y    1.447633
dtype: float64