In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
X, y = load_boston(return_X_y=True)
load_boston()

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [2]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [3]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [4]:
load_boston()['feature_names']

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [5]:
df=pd.DataFrame(data=X, columns=load_boston()['feature_names'])
df['house-price']=y
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  house-price  
0       15.3  396.90   4.98         24.0  
1       17.8  396.90   9.14         21.6  
2       17.8  392.83   4.03         34.7  
3       18.7  394.63   2.94         33.4  
4       18.7  396.90   5.33         36.2  
..       ...     ...    ...          ...  
501     21.0  391.99   9.67         22.4  
502     21.0  396.90   9.08         20.6  
503     21.0  396.90   5.64         23.9  
504     21.0  393.45   6.48         22.0  
505     21.0  396.90   7.88         11.9  

[506 rows x 14 columns]

In [6]:
from sklearn.model_selection import train_test_split
X, y = df.iloc[:,:-1],df.iloc[:,[-1]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=5)

In [7]:
from sklearn.preprocessing import StandardScaler
data = X_train
scaler = StandardScaler()

In [9]:
X_train = pd.DataFrame(scaler.fit_transform(data),index=X_train.index, columns=X_train.columns)
X_train

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
445  0.875509 -0.499618  1.069608 -0.251124  1.645428  0.233772  0.969882   
428  0.474665 -0.499618  1.069608 -0.251124  1.113435 -0.149715  0.383159   
481  0.273444 -0.499618  1.069608 -0.251124 -0.168580  0.653301  0.270733   
55  -0.417342  3.445319 -1.442682 -0.251124 -1.293614  1.372699 -1.591321   
488 -0.400634 -0.499618  2.504352 -0.251124  0.502952 -1.215116  0.896102   
..        ...       ...       ...       ...       ...       ...       ...   
486  0.271452 -0.499618  1.069608 -0.251124  0.276201 -0.263608  0.442885   
189 -0.408780  1.472851 -1.112274 -0.251124 -0.997094  1.280432 -0.994058   
495 -0.397222 -0.499618 -0.182072 -0.251124  0.293643 -0.903713 -1.348902   
206 -0.391072 -0.499618 -0.048122 -0.251124 -0.543592  0.042029 -0.516248   
355 -0.406003  3.006992 -1.339987 -0.251124 -1.206402 -0.520227 -1.675640   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
445 -0.900522  1.654486  1.538813  0.810913 -3.463820  1.611369  
428 -0.926152  1.654486  1.538813  0.810913 -2.872888  1.265636  
481 -0.241993  1.654486  1.538813  0.810913  0.389957 -0.671032  
55   2.387078 -0.527917 -1.061095 -0.265106  0.421447 -1.082820  
488 -0.982361 -0.642780  1.804713  0.764129  0.412198  0.779361  
..        ...       ...       ...       ...       ...       ...  
486 -0.137024  1.654486  1.538813  0.810913  0.385663  0.346492  
189  0.363219 -0.527917 -0.044767 -1.528259  0.432127 -1.001306  
495 -0.503239 -0.413054 -0.086129  0.343078  0.392379  0.714712  
206  0.259426 -0.642780 -0.759742  0.062378  0.409776 -0.217082  
355  3.312831 -0.642780 -0.422936  1.653014  0.202448 -0.976008  

[354 rows x 13 columns]

In [10]:
X_test = pd.DataFrame(scaler.transform(X_test),index=X_test.index, columns=X_test.columns)
X_test

CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
226 -0.372580 -0.499618 -0.701496 -0.251124 -0.412774  2.513068  0.678277   
292 -0.414547  3.006992 -0.887537 -0.251124 -1.223845  0.480299 -1.538621   
90  -0.413251 -0.499618 -1.116739 -0.251124 -0.543592  0.173222 -0.038438   
373  0.928431 -0.499618  1.069608 -0.251124  1.017502 -2.005157  1.152574   
273 -0.392019  0.377035 -0.588384  3.982103 -0.761621  2.009922 -0.540841   
..        ...       ...       ...       ...       ...       ...       ...   
60  -0.400820  0.596198 -0.860747 -0.251124 -0.857555 -0.801354 -0.034925   
108 -0.403404 -0.499618 -0.350252 -0.251124 -0.273235  0.255397  1.050688   
298 -0.411089  2.568666 -1.290873 -0.251124 -1.319778  0.069421 -1.654560   
138 -0.388633 -0.499618  1.633683 -0.251124  0.633770 -0.634119  1.089334   
370  0.374190 -0.499618  1.069608  3.982103  0.694818  1.036788  1.064741   

          DIS       RAD       TAX   PTRATIO         B     LSTAT  
226 -0.298839 -0.183327 -0.582476 -0.499023  0.327307 -1.318931  
292  0.632747 -0.642780 -0.948826  0.343078  0.432127 -1.098280  
90  -0.359311 -0.872507 -0.801104 -0.311890  0.380158 -0.520652  
373 -1.299276  1.654486  1.538813  0.810913  0.432127  3.127817  
273  0.265111 -0.757644 -1.078822  0.062378  0.364633 -0.834061  
..        ...       ...       ...       ...       ...       ...  
60   1.666116 -0.183327 -0.718380  0.576996  0.412418  0.089300  
108 -0.682450 -0.527917 -0.127492  1.138397  0.413850 -0.034377  
298  1.961322 -0.527917 -0.281123 -1.715392  0.116567 -1.060334  
138 -1.056995 -0.642780  0.185679  1.278747  0.378616  1.237528  
370 -1.285457  1.654486  1.538813  0.810913  0.378726 -1.342823  

[152 rows x 13 columns]

In [11]:
#without train test split
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0, max_iter=1000)
clf.fit(X_train, y_train)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [12]:
clf.coef_

array([[-1.26014432,  0.92609531, -0.19903831,  0.19029987, -1.45286471,
         2.80923459, -0.30605221, -2.69278177,  2.65969162, -2.03741778,
        -2.08039818,  1.14440037, -3.27442671]])

In [13]:
clf.intercept_

array([22.55621469])

In [14]:
clf.predict(X_test)

array([[37.34211639],
       [31.48721693],
       [27.14478647],
       [ 6.52846628],
       [33.6803037 ],
       [ 5.57155703],
       [27.10468488],
       [29.81071816],
       [26.48713996],
       [22.34062336],
       [32.26568027],
       [21.73067695],
       [23.41474436],
       [33.49934547],
       [28.26332804],
       [15.48259682],
       [ 0.16949023],
       [18.75526231],
       [14.64832236],
       [10.82136218],
       [ 3.37905818],
       [19.43636055],
       [38.28563489],
       [24.40947635],
       [32.00813353],
       [11.36371822],
       [24.91800812],
       [23.43389905],
       [22.75582889],
       [21.22786259],
       [16.02200743],
       [ 7.71877929],
       [17.57217901],
       [22.82056844],
       [29.23890763],
       [18.85023074],
       [28.32295207],
       [ 8.623754  ],
       [41.60442366],
       [34.15239996],
       [20.08577892],
       [ 4.36960244],
       [29.55918381],
       [11.93388627],
       [27.19958551],
       [30

In [15]:
def MeanSquaredError(Y_true,Y_pred):
    MSE = np.square(np.subtract(Y_true,Y_pred)).mean() 
    return MSE

Y_true = [1,1,2,2,4]
Y_pred = [0.6,1.29,1.99,2.69,3.4]

MeanSquaredError(Y_true,Y_pred)   

0.21606

In [16]:
MeanSquaredError(y_test,clf.predict(X_test))

house-price    30.722177
dtype: float64