In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('C:\\Users\\soham\\Downloads\\LinearRegression.csv')
df 

x  y
0  2  1
1  3  2
2  1  2
3  1  1
4  0  1
5  5  3
6  4  3
7  6  7
8  5  6
9  3  5

In [2]:
def MeanSquaredError(Y_true,Y_pred):
    MSE = np.square(np.subtract(Y_true,Y_pred)).mean() 
    return MSE

Y_true = [1,1,2,2,4]
Y_pred = [0.6,1.29,1.99,2.69,3.4]

MeanSquaredError(Y_true,Y_pred)   

0.21606

In [3]:
def stoc_gradient_descent_regularization(X, y_true, lr=0.05, epoch=100, lamda=0.1): #updating m and c till fixed number of iteration/epoch,by default epoch=100
    
    '''
    Gradient Descent for a single feature
    '''
    
    m, c = 3,2 # parameters
    logs, mse = [], [] # lists to store learning process
    #N = len(X) # number of samples
    
    for ep in range(epoch):
        
        logs.append((m, c))
        
        # lists for plotting purposes
        m_list.append(m)
        c_list.append(c)
        
        MSE_complete = MeanSquaredError(y_true, (m_list[-1]*X)+c_list[-1]) 
        #MSE of complete dataset using latest values of 'm' and 'c' after applying
        #stochastic GD on all the points one by one.
        print('The Mean Squared Error of epoch ',ep,' is ',MSE_complete)
        mse.append(MSE_complete)
        mse_list.append(MSE_complete) #for plotting purposes
        
        for n,i in enumerate(X):
            y_pred = (m*i + c)
            diff = y_pred - y_true[n] 

            MSE_single= MeanSquaredError(y_true, y_pred) #for a single point
            
            m -= lr * ((2 * i * diff) + 2*lamda*m)  # acc to gradient descent eqn, this is m(new) = (m(old) + α * ∂(MSE)/∂m ) , where α is learning rate
            # added the regularization factor '2*lamda*m', in the calculation of ∂(MSE)/∂m, no changes in clculation of 'c'
            c -= lr * (2 * diff)  # acc to gradient descent eqn, this is c(new) = (c(old) + α * ∂(MSE)/∂c ) , where α is learning rate
        
    print('The Final Value of m is : ',m)
    print('The Final Value of c is : ',c)
    print('The Minimum Value of MSE is : ',min(mse))
    
           
    return logs, mse

In [18]:
def stoc_gradient_descent_regularization_test(X, y_true, lr=0.05, epoch=100, lamda=0.1): #updating m and c till fixed number of iteration/epoch,by default epoch=100
    
    '''
    Gradient Descent for a single feature
    '''
    
    m, c = 3,2 # parameters
    logs, mse = [], [] # lists to store learning process
    #N = len(X) # number of samples
    
    for ep in range(epoch):
        
        logs.append((m, c))
        
        # lists for plotting purposes
        m_list.append(m)
        c_list.append(c)
        
        MSE_complete = MeanSquaredError(y_true, (m_list[-1]*X)+c_list[-1]) 
        #MSE of complete dataset using latest values of 'm' and 'c' after applying
        #stochastic GD on all the points one by one.
        print('The Mean Squared Error of epoch ',ep,' is ',MSE_complete)
        mse.append(MSE_complete)
        mse_list.append(MSE_complete) #for plotting purposes
        
        for n,i in enumerate(X):
            y_pred = (m*i + c)
            diff = y_pred - y_true[n] 

            MSE_single= MeanSquaredError(y_true, y_pred) #for a single point
            
            m -= lr * ((2 * i * diff) + 2*lamda*m)  # acc to gradient descent eqn, this is m(new) = (m(old) + α * ∂(MSE)/∂m ) , where α is learning rate
            # added the regularization factor '2*lamda*m', in the calculation of ∂(MSE)/∂m, no changes in clculation of 'c'
            c -= lr * ((2 * diff) + 2*lamda*c) # acc to gradient descent eqn, this is c(new) = (c(old) + α * ∂(MSE)/∂c ) , where α is learning rate
        
    print('The Final Value of m is : ',m)
    print('The Final Value of c is : ',c)
    print('The Minimum Value of MSE is : ',min(mse))
    
           
    return logs, mse

In [ ]:
# lists for plotting purposes
mse_list=[]
m_list=[]
c_list=[]

X=df['x']
y=df['y']
stoc_gradient_descent_regularization(X, y, lr=0.001, epoch=200) #keep the learning rate low in case of Stochastic GD

In [20]:
# lists for plotting purposes
mse_list=[]
m_list=[]
c_list=[]

X=df['x']
y=df['y']
stoc_gradient_descent_regularization_test(X, y, lr=0.001, epoch=200) #keep the learning rate low in case of Stochastic GD

The Mean Squared Error of epoch  0  is  79.9
The Mean Squared Error of epoch  1  is  47.03028191586601
The Mean Squared Error of epoch  2  is  28.020878301684455
The Mean Squared Error of epoch  3  is  17.01616173594128
The Mean Squared Error of epoch  4  is  10.63688239098411
The Mean Squared Error of epoch  5  is  6.932284366701715
The Mean Squared Error of epoch  6  is  4.775783572586476
The Mean Squared Error of epoch  7  is  3.5164150164996903
The Mean Squared Error of epoch  8  is  2.7777722045211704
The Mean Squared Error of epoch  9  is  2.3420059741712493
The Mean Squared Error of epoch  10  is  2.082882497206221
The Mean Squared Error of epoch  11  is  1.92714058414494
The Mean Squared Error of epoch  12  is  1.8321760185140405
The Mean Squared Error of epoch  13  is  1.7731477878706001
The Mean Squared Error of epoch  14  is  1.7355230802505077
The Mean Squared Error of epoch  15  is  1.7107630344025666
The Mean Squared Error of epoch  16  is  1.6938231376203252
The Mean Squ

The Mean Squared Error of epoch  147  is  1.4716614355131845
The Mean Squared Error of epoch  148  is  1.4712365106303356
The Mean Squared Error of epoch  149  is  1.470818732116943
The Mean Squared Error of epoch  150  is  1.4704079880418657
The Mean Squared Error of epoch  151  is  1.4700041681734728
The Mean Squared Error of epoch  152  is  1.4696071639542112
The Mean Squared Error of epoch  153  is  1.4692168684755549
The Mean Squared Error of epoch  154  is  1.4688331764533253
The Mean Squared Error of epoch  155  is  1.4684559842033749
The Mean Squared Error of epoch  156  is  1.4680851896176352
The Mean Squared Error of epoch  157  is  1.4677206921405235
The Mean Squared Error of epoch  158  is  1.4673623927456925
The Mean Squared Error of epoch  159  is  1.4670101939131341
The Mean Squared Error of epoch  160  is  1.466663999606618
The Mean Squared Error of epoch  161  is  1.4663237152514654
The Mean Squared Error of epoch  162  is  1.4659892477126573
The Mean Squared Error of 

([(3, 2),
  (2.440593930321635, 1.8541286455147492),
  (2.0162858633988447, 1.7415194275756802),
  (1.6945528792002529, 1.6541794711338482),
  (1.4507007229427986, 1.5860397766439749),
  (1.2659793551278735, 1.5324921218502583),
  (1.1261521103633205, 1.4900374366341402),
  (1.0204092761183268, 1.4560188180756972),
  (0.9405431855712345, 1.4284188118556025),
  (0.880321875099704, 1.4057054903502157),
  (0.8350135096195687, 1.3867155814944625),
  (0.8010252842167962, 1.3705657298665157),
  (0.7756292463118949, 1.356585118244903),
  (0.7567541155846784, 1.3442643079266394),
  (0.7428272152392436, 1.3332163937640762),
  (0.7326544522330948, 1.3231475096260332),
  (0.7253291876470295, 1.3138344335285759),
  (0.7201630430065489, 1.3051075834633086),
  (0.7166333623189095, 1.296838106320322),
  (0.7143433206034453, 1.2889280746508636),
  (0.7129916347587433, 1.2813030431769918),
  (0.7123495653737165, 1.2739063970300102),
  (0.7122434544684988, 1.2666950604279854),
  (0.7125414666031599, 1.2

# using sklearn SGDRegressor:-

In [5]:
X=df['x']
y=df['y']
np.array(X).reshape((10,1))

array([[2],
       [3],
       [1],
       [1],
       [0],
       [5],
       [4],
       [6],
       [5],
       [3]], dtype=int64)

In [6]:
from sklearn.linear_model import SGDRegressor
reg = SGDRegressor(max_iter=100, alpha=0.1, learning_rate='constant', eta0=0.001 )
reg.fit(np.array(X).reshape(10,1), np.array(y))

SGDRegressor(alpha=0.1, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.001, fit_intercept=True, l1_ratio=0.15,
             learning_rate='constant', loss='squared_loss', max_iter=100,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.001, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [7]:
reg.coef_

array([0.91919702])

In [8]:
reg.intercept_

array([0.24989906])

In [9]:
reg.n_iter_

37

In [14]:
MeanSquaredError(y,reg.predict(np.array(X).reshape(10,1)))

1.457420531283298